openapi: 3.0.3
info:
  title: 实时报表_广告组层级实时数据
  version: 1.0.0
  x-api-id: xhs.jg.report.realtime.campaign_group.v1
  x-category: realtime_reports
servers:
- url: https://adapi.xiaohongshu.com
paths:
  /api/open/jg/data/report/realtime/campaignGroup:
    post:
      summary: 实时报表_广告组层级实时数据
      operationId: xhs_jg_report_realtime_campaign_group_v1
      tags:
      - realtime_reports
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
      x-notes: 'filter字段: name, campaign_group_id, group_create_begin_time, group_create_end_time,
        group_filter_state'
      x-pagination:
        type: page
        list_path: data.data_list
        page_param: page_num
        size_param: page_size
        start_page: 1
        page_size: 20
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                advertiser_id:
                  type: integer
                  default: 7152346
                  x-source:
                    type: var
                    name: advertiser_id
                start_date:
                  type: string
                  default: '2025-10-28'
                  x-source:
                    type: var
                    name: start_date
                end_date:
                  type: string
                  default: '2025-10-28'
                  x-source:
                    type: var
                    name: end_date
                page_num:
                  type: integer
                  default: 1
                  x-source:
                    type: var
                    name: page_num
                page_size:
                  type: integer
                  default: 20
                data_caliber:
                  type: string
                  x-source:
                    type: var
                    name: data_caliber
                columns:
                  type: array
                  items:
                    type: string
                  default: &id001
                  - campaign_group_id
                  - campaign_group_name
                  - impression
                  - click
                  - fee
                  x-source:
                    type: var
                    name: columns
                filter:
                  type: string
                  x-source:
                    type: var
                    name: filter
            example:
              advertiser_id: 7152346
              start_date: '2025-10-28'
              end_date: '2025-10-28'
              page_num: 1
              page_size: 20
              columns:
              - campaign_group_id
              - campaign_group_name
              - impression
              - click
              - fee
